if (window.CaseAccess?.allowed) {
const suspects = [
  ['camila-duarte', 'camila_duarte.png'], ['daniel-rocha', 'daniel_rocha.png'],
  ['rafael-martins', 'rafael_martins.png'], ['marina-albuquerque', 'marina_alburquerque.png'],
  ['helena-martins', 'helena_martins.png'], ['eduardo-alves', 'eduardo_alves.png'],
  ['gabriel-monteiro', 'gabriel_monteiro.png'], ['lucas-martins', 'lucas_martins.png']
];
const interrogations = {
  'camila-duarte': [
    { fase: 1, perguntas: [{ pergunta: 'Por que você entrou no banheiro depois que Rafael abriu a porta?', resposta: 'Eu fiquei muito abalada com o que vi e precisei me afastar por alguns minutos. Fui ao banheiro para respirar e tentar me acalmar.' }, { pergunta: 'O que aconteceu entre você e Isabela antes do apagão?', resposta: 'Nós discutimos. Ela descobriu que eu tinha contado uma coisa pessoal dela para outra pessoa e ficou muito magoada. Disse que já não sabia em quem podia confiar.' }] },
    { fase: 2, perguntas: [{ pergunta: 'A perícia encontrou seu sangue no banheiro. Você consegue explicar isso?', resposta: 'Eu me machuquei antes de chegar ao quarto e acabei usando o banheiro. Foi uma coisa pequena e achei que não tinha importância para mencionar.' }, { pergunta: 'O que exatamente você contou sobre Isabela para outra pessoa?', resposta: 'Eu contei que ela estava pensando em não se casar com Gabriel. Ela tinha começado a desconfiar dele e dizia que tinha descoberto coisas sobre o passado dele. Eu achei que ela só estivesse nervosa com o casamento.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Você percebeu alguma coisa estranha quando chegou ao quarto 307?', resposta: 'Naquele momento, eu estava mais preocupada com Isabela. Rafael estava tentando ajudar e todo mundo falava ao mesmo tempo. Só depois percebi que algumas coisas no quarto estavam fora do lugar.' }, { pergunta: 'Você viu alguém perto do quarto antes de entrar?', resposta: 'Vi algumas pessoas no corredor, mas estava tudo acontecendo muito rápido. Eu não prestei atenção suficiente para saber exatamente quem estava vindo de cada lugar.' }] }
  ],
  'rafael-martins': [
    { fase: 1, perguntas: [{ pergunta: 'As gavetas do quarto 307 foram encontradas mexidas. Você sabe o que Isabela guardava ali?', resposta: 'Alguns documentos pessoais, papéis do casamento e coisas que ela estava investigando. Eu não sabia exatamente o que ela tinha encontrado, mas sabia que ela estava guardando informações que poderiam causar problemas para algumas pessoas.' }, { pergunta: 'Quando você e Isabela discutiram sobre dinheiro, o que exatamente ela tinha descoberto?', resposta: 'Ela tinha percebido que havia coisas erradas na minha situação financeira. Disse que os números não batiam e que eu estava escondendo a verdadeira dimensão dos meus problemas. Eu achei que ela estava apenas desconfiada, mas pelo jeito ela já tinha encontrado alguma coisa.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Isabela estava reunindo provas contra você. Quem, além de você, sabia que ela estava fazendo isso?', resposta: 'Eu não sei exatamente quem sabia. Isabela não confiava em ninguém quando estava investigando alguma coisa. Mas, se ela já estava procurando documentos e fazendo anotações sobre as pessoas, é possível que alguém próximo tenha percebido o que ela estava fazendo.' }, { pergunta: 'Você entrou no quarto assim que a porta foi arrombada. O que você lembra sobre o armário de casacos naquele momento?', resposta: 'Eu estava preocupado com a Isabela e fui direto até ela. Não prestei atenção no armário. Só lembro que ele estava fechado quando olhei para o quarto depois que a situação começou a ser controlada.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Se alguém tivesse procurado alguma coisa no quarto naquela noite, o que você acha que essa pessoa estaria procurando?', resposta: 'Provavelmente alguma coisa que Isabela tinha descoberto. Ela estava juntando documentos e informações sobre várias pessoas. Se alguém entrou ali para procurar alguma coisa, não acho que estivesse atrás de dinheiro ou objetos pessoais.' }, { pergunta: 'Se você tivesse que apontar alguém que realmente tinha motivos para querer Isabela morta, quem seria?', resposta: 'Eduardo. Ele ainda tinha sentimentos por ela, não aceitava o casamento e foi a última pessoa que esteve sozinho com ela antes de tudo acontecer. Todo mundo está olhando para a minha situação financeira, mas Eduardo tinha muito mais a perder emocionalmente.' }] }
  ],
  'eduardo-alves': [
    { fase: 1, perguntas: [{ pergunta: 'Você disse que recebeu uma carta de Isabela pedindo que fosse ao hotel. O que exatamente estava escrito nela?', resposta: 'Era um pedido para que eu fosse ao hotel naquela noite, por volta das 21h, porque ela precisava conversar comigo pessoalmente. O pedido era direto e dizia para eu não chegar atrasado. Foi por isso que eu fui.' }, { pergunta: 'Quando você percebeu que Isabela não tinha chamado você, por que continuou a conversa?', resposta: 'Porque ela estava diferente e claramente havia alguma coisa acontecendo. Ela disse que não sabia mais em quem confiar e que estava começando a questionar algumas coisas que tinha descoberto.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Você disse que ouviu um barulho antes de sair do quarto. O que aconteceu exatamente?', resposta: 'Nós estávamos conversando quando ouvimos um barulho vindo de dentro do quarto, como se algum objeto tivesse caído. Isabela parou imediatamente e ficou olhando na direção de onde veio o som.' }, { pergunta: 'Você ainda tinha sentimentos por Isabela. O que vocês discutiram sobre Gabriel naquela noite?', resposta: 'Eu disse que achava que ela estava cometendo um erro ao se casar sem esclarecer algumas coisas sobre Gabriel. Ficou claro para mim que ela também estava desconfiada.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Isabela recebeu uma mensagem dizendo “Você não sabe a história inteira”. Ela falou sobre isso?', resposta: 'Sim. Ela perguntou se eu sabia alguma coisa sobre aquilo. Eu disse que não tinha enviado a mensagem e que não sabia quem tinha escrito.' }, { pergunta: 'Se não foi você, quem poderia ter interesse em impedir Isabela de continuar investigando?', resposta: 'Rafael tinha um problema financeiro que poderia ficar muito maior se ela encontrasse provas. Gabriel também tinha motivos para estar preocupado, porque Isabela estava investigando o passado dele.' }] }
  ],
  'marina-albuquerque': [
    { fase: 1, perguntas: [{ pergunta: 'O telefone que enviou a mensagem “Você não sabe a história inteira” foi rastreado. Você enviou essa mensagem?', resposta: 'Enviei. Eu sabia que Isabela estava desconfiada de algumas coisas e achei que ela precisava saber que havia algo que ainda não tinha descoberto.' }, { pergunta: 'Naquela semana, Isabela estava investigando pessoas próximas. O que você percebeu?', resposta: 'Ela estava diferente. Fazia perguntas, observava as pessoas e parecia estar decepcionada com várias pessoas. Eu percebi que ela estava tentando descobrir mais sobre Gabriel.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Por que você mandou uma mensagem anônima para Isabela em vez de falar pessoalmente?', resposta: 'Porque eu não queria ser colocada no meio do casamento. Se falasse diretamente, Isabela iria querer saber como eu descobri aquilo e Gabriel é meu irmão; isso destruiria nosso relacionamento.' }, { pergunta: 'Isabela chegou a perguntar a você alguma coisa sobre Gabriel antes de morrer?', resposta: 'Sim. Ela perguntou se eu sabia de alguma coisa que ela ainda não tinha descoberto sobre ele. Eu disse que não sabia de nada. Eu menti porque não estava preparada para contar.' }] },
    { fase: 3, perguntas: [{ pergunta: 'O que você sabia sobre Gabriel que Isabela ainda não sabia?', resposta: 'Eu sabia que Gabriel estava tendo um caso com outra mulher. Eu não sabia exatamente há quanto tempo aquilo acontecia, mas tinha motivos suficientes para ela cancelar o casamento.' }, { pergunta: 'Você chegou a descobrir como Isabela estava conseguindo informações sobre Gabriel?', resposta: 'Não exatamente. Acho que poderia ter vindo do Lucas, ele fica ouvindo escondido as pessoas conversando.' }] }
  ],
  'lucas-martins': [
    { fase: 1, perguntas: [{ pergunta: 'Você disse que ouviu uma discussão entre Isabela e Camila. O que exatamente você conseguiu ouvir?', resposta: 'Eu não ouvi tudo, só alguns trechos. A Camila estava tentando explicar por que tinha contado uma coisa pessoal da Isabela para outra pessoa. Isabela estava muito magoada e disse que já não sabia o que Camila ainda poderia estar escondendo. Pelo tom das duas, parecia que o problema era maior do que uma simples fofoca.' }, { pergunta: 'Você também ouviu uma discussão entre Isabela e Marina. O que chamou sua atenção nessa conversa?', resposta: 'A Marina estava muito irritada com as mudanças do casamento. Ela reclamava que tinha colocado dinheiro e tempo naquilo e que Isabela estava simplesmente mudando tudo. Mas teve uma hora em que Isabela respondeu que o problema não era o casamento em si e que havia coisas muito mais importantes acontecendo. Foi aí que percebi que ela estava escondendo alguma coisa de todo mundo.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Você mencionou ter ouvido uma discussão entre Isabela e Helena. O que realmente foi dito naquela conversa?', resposta: 'Essa foi uma das conversas que mais me chamou atenção. Eu ouvi Helena dizendo que estava cansada de tentar ajudar e que Isabela estava jogando tudo fora. Mas não parecia ser só sobre a cerimônia. Em determinado momento, Isabela falou como se tivesse descoberto uma coisa muito pessoal sobre a mãe. Pelo que consegui ouvir, parecia que Helena estava escondendo um relacionamento ou algum tipo de traição contra o pai dela. Isabela estava muito decepcionada. Eu não ouvi o nome da outra pessoa, então não posso afirmar com quem seria.' }, { pergunta: 'Você ouviu alguma coisa que explique por que Isabela estava investigando Gabriel?', resposta: 'Sim. Eu ouvi comentários sobre ela estar tentando descobrir coisas do passado dele. E depois ouvi Isabela dizer que não entendia por que tantas pessoas estavam tentando esconder coisas sobre Gabriel. Mais tarde, também fiquei sabendo que Gabriel vinha evitando conversar com ela. Para mim, estava claro que ela tinha descoberto alguma coisa séria sobre ele.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Entre tudo o que você ouviu naquele dia, por que Rafael é a pessoa que mais chama sua atenção?', resposta: 'Porque o problema dele com Isabela não era só uma discussão de família. Ela tinha descoberto que a situação financeira dele era muito pior do que ele contava e estava ameaçando revelar isso. E eu conheço o Rafael. Ele fica desesperado quando sente que vai perder o controle de alguma situação. Depois que Isabela morreu, ele foi justamente a primeira pessoa a chegar ao quarto e a forçar a porta. Eu não estou dizendo que ele matou ela, mas, se querem saber de quem eu desconfio, é dele.' }, { pergunta: 'Você também sabia que Gabriel estava escondendo coisas de Isabela. O que você ouviu sobre uma possível traição?', resposta: 'Eu ouvi o suficiente para entender que Gabriel estava traindo Isabela. Não sei todos os detalhes, mas não parecia ser apenas um boato. Isabela estava investigando o passado dele justamente porque desconfiava que havia alguma coisa errada. E, pelo que ouvi naquele dia, algumas pessoas próximas sabiam mais do que estavam admitindo.' }] }
  ],
  'helena-martins': [
    { fase: 1, perguntas: [{ pergunta: 'Lucas afirmou ter ouvido você discutindo com Isabela pouco antes do apagão. Sobre o que vocês estavam discutindo?', resposta: 'Era uma discussão familiar. Isabela estava fazendo muitas perguntas sobre o meu casamento e sobre algumas coisas que eu preferia manter em particular. Eu fiquei nervosa porque já estava emocionalmente abalada. Não queria discutir com ela, muito menos naquele momento. Se eu soubesse que seria a última conversa que teríamos, teria escolhido outras palavras.' }, { pergunta: 'Em uma anotação encontrada no quarto, Isabela escreveu que você estava diferente e perguntou se você tinha um amante. Ela tinha algum motivo para desconfiar disso?', resposta: 'Isabela sempre foi muito observadora. Ela percebeu que meu casamento não estava bem e começou a fazer perguntas. Eu tentei esconder meus problemas pessoais dela porque não queria colocar minha filha no meio do meu casamento. Mas acho que ela percebeu que eu estava escondendo alguma coisa.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Então Isabela estava certa ao desconfiar que você escondia alguma coisa do seu marido?', resposta: 'Sim. Eu não vou mentir sobre isso. Meu casamento estava passando por uma fase muito complicada e eu cometi um erro. Havia outra pessoa. Foi algo que eu tentei esconder e do qual me arrependo. Eu não queria que minha família descobrisse.' }, { pergunta: 'Isabela chegou a descobrir quem era essa pessoa?', resposta: 'Ela descobriu que eu estava tendo um caso, mas eu não sei exatamente o quanto ela sabia. Ela me confrontou naquela noite e estava muito decepcionada comigo. Eu pedi que ela não contasse nada ao pai. Não porque eu quisesse proteger a mentira, mas porque tinha medo de destruir minha família de uma vez.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Por que você ficou tão nervosa quando Isabela começou a investigar sua vida pessoal?', resposta: 'Porque ela estava chegando perto demais de algo que eu passei muito tempo tentando esconder. Eu sabia que, se aquilo viesse à tona, meu casamento acabaria e minha família nunca mais seria a mesma. Mas, apesar de tudo, ela era minha filha. Eu jamais quis que nada acontecesse com ela.' }, { pergunta: 'Depois que Eduardo deixou o quarto 307, o que você fez até o momento em que o apagão aconteceu?', resposta: 'Voltei para o meu quarto. Eu precisava ficar sozinha depois da discussão com Isabela. Fiquei lá tentando me acalmar. Quando ouvi o grito, saí imediatamente para o corredor. Foi quando percebi que alguma coisa tinha acontecido com minha filha.' }] }
  ],
  'gabriel-monteiro': [
    { fase: 1, perguntas: [{ pergunta: 'Gabriel, você era o noivo de Isabela. Antes de falarmos sobre as suspeitas, queremos saber: o que Isabela significava para você?', resposta: 'Ela era a pessoa que eu escolhi para construir minha vida. Eu amava a Isabela de verdade. Sei que as coisas entre nós não estavam perfeitas e que eu cometi erros que não consigo apagar, mas isso não muda o que eu sentia por ela. Eu estava prestes a me casar com a mulher que eu amava. Não consigo aceitar que ela não esteja mais aqui.' }, { pergunta: 'Foi descoberto que você costumava usar dinheiro para conseguir o que queria, inclusive pagando pessoas para facilitar algumas situações. Você confirma isso?', resposta: 'Eu confirmo que já fiz coisas assim. Em alguns momentos, usei dinheiro para resolver problemas que eu não queria enfrentar de outra maneira. Foi errado, e eu sei disso. Mas existe uma diferença enorme entre usar dinheiro para conseguir uma vantagem e pagar alguém para tirar a vida de uma pessoa. Eu poderia ter feito escolhas melhores no passado, mas jamais faria uma coisa dessas com a Isabela.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Daniel afirmou que você já havia pago um professor para conseguir uma aprovação. Além disso, existem relatos de que você usava dinheiro e influência sempre que alguma coisa não saía como queria. Se você não teve tempo de chegar ao quarto 307, isso realmente prova que não teve envolvimento?', resposta: 'Eu estava no restaurante. Não teria como chegar ao quarto naquele intervalo sem que alguém percebesse. Mas eu entendo a pergunta. Se eu realmente quisesse fazer alguma coisa contra Isabela, alguém poderia pensar que eu simplesmente teria pagado outra pessoa para fazer isso por mim. Só que eu nunca faria isso. Nunca. Eu errei com ela, mas não desse jeito. Eu amava aquela mulher. Eu estava esperando o momento de chamá-la de minha esposa.' }, { pergunta: 'Você admite que traiu Isabela durante o relacionamento?', resposta: 'Sim. Eu traí. E talvez seja a coisa de que mais me arrependo. Não vou tentar inventar uma desculpa para o que fiz. Foi uma escolha minha e eu machuquei a pessoa que mais confiava em mim. Eu queria deixar aquilo para trás e reconstruir nossa relação. Eu não queria perder a Isabela por causa de um erro que cometi.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Isabela estava investigando seu passado e descobrindo coisas que você preferia esconder. O que você acha que ela estava prestes a descobrir?', resposta: 'Eu não sei exatamente o que ela tinha descoberto. Ela fazia muitas perguntas e eu percebia que estava desconfiada de mim. Eu tinha medo de que ela descobrisse tudo que eu fiz de errado e decidisse não se casar comigo. Mas eu ainda acreditava que conseguiria explicar as coisas e consertar nossa relação. Eu só queria uma chance de fazer as coisas direito.' }, { pergunta: 'Depois de tudo que descobrimos sobre você — dinheiro, influência, mentiras e uma traição — por que deveríamos acreditar que você não seria capaz de matar Isabela?', resposta: 'Porque eu posso ter sido um homem que fez escolhas ruins, mas eu não sou um assassino. Eu menti, eu escondi coisas e traí a mulher que amava. Vou carregar arrependimento por isso. Mas matar a Isabela? Nunca. Eu queria me casar com ela. Queria ter uma vida com ela. Se eu pudesse voltar algumas horas no tempo e mudar qualquer coisa, eu mudaria tudo que fiz de errado. Só queria que ela estivesse viva para que eu pudesse pedir perdão.' }] }
  ],
  'daniel-rocha': [
    { fase: 1, perguntas: [{ pergunta: 'O que exatamente Isabela estava tentando descobrir sobre o passado de Gabriel?', resposta: 'Ela queria saber por que tanta gente evitava falar sobre ele. Gabriel não tinha exatamente um passado limpo. Eu sabia de algumas coisas, mas preferi não contar porque não queria me envolver.' }, { pergunta: 'Você sabia que Gabriel costumava usar dinheiro para conseguir o que queria?', resposta: 'Sim. Isso não era novidade para quem convivia com ele. Quando aparecia algum problema, ele procurava uma maneira de resolver com dinheiro. Já vi ele oferecer dinheiro para pessoas que poderiam facilitar as coisas para ele.' }] },
    { fase: 2, perguntas: [{ pergunta: 'O que você sabe sobre Gabriel ter comprado um professor na faculdade?', resposta: 'Eu soube que ele pagou um professor para conseguir uma aprovação que não teria conseguido sozinho. Gabriel não queria correr o risco de reprovar, então resolveu o problema do jeito que sempre fazia: pagando alguém.' }, { pergunta: 'Esse foi um caso isolado ou Gabriel já tinha feito isso antes?', resposta: 'Não acho que tenha sido um caso isolado. Ele tinha esse costume de usar dinheiro e influência para conseguir vantagens. Se alguém podia atrapalhar o que ele queria, Gabriel tentava encontrar uma forma de fazer essa pessoa mudar de posição.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Você sabia que Gabriel tinha traído Isabela durante o relacionamento?', resposta: 'Sim. Eu sabia que ele tinha se envolvido com outra mulher enquanto ainda estava com Isabela. Não conheço todos os detalhes, mas sei que aconteceu.' }, { pergunta: 'O que você acha que Gabriel mais tinha medo que Isabela descobrisse?', resposta: 'Não era apenas a traição. Era o conjunto de coisas. Quanto mais ela investigasse, mais perceberia que Gabriel tinha construído muita coisa usando dinheiro, influência e mentiras. E eu acho que ele sabia que, se ela juntasse tudo, o casamento provavelmente acabaria.' }] }
  ]
};


const questions = document.querySelector('#questions'), name = document.querySelector('#name'), role = document.querySelector('#role'), area = document.querySelector('#suspects');
const renderSuspect = (suspect) => {
  name.textContent = suspect.nome; role.textContent = `${suspect.papel} · ${suspect.idade} anos`; questions.innerHTML = '';
  const phases = interrogations[suspect.id] || suspect.fases;
  phases.forEach((phase) => { const group = document.createElement('div'); group.className = 'phase'; group.innerHTML = `<p>fase ${phase.fase} · escolha uma pergunta</p>`; phase.perguntas.forEach((item, index) => { const button = document.createElement('button'); button.innerHTML = `<i>${String(index + 1).padStart(2, '0')}</i>${item.pergunta}<strong>+</strong>`; button.onclick = () => { group.querySelectorAll('button').forEach(other => { other.disabled = true; other.style.opacity = other === button ? '1' : '.35'; }); button.classList.add('asked'); const response = document.createElement('div'); response.className = 'phase-answer'; response.innerHTML = `<span>resposta de ${suspect.nome}</span><p>“${item.resposta}”</p>`; group.append(response); }; group.append(button); }); questions.append(group); });
};
Promise.all(suspects.map(([id, photo]) => fetch(`suspeitos/${id}.json`).then(response => response.json()).then(data => ({ ...data, photo })))).then((data) => { area.innerHTML = ''; data.forEach((suspect, index) => { const button = document.createElement('button'); button.className = `suspect${index === 0 ? ' active' : ''}`; button.innerHTML = `<span class="suspect-no">${String(index + 1).padStart(2, '0')}</span><span class="portrait"><img src="images/${suspect.photo}" alt="Foto de ${suspect.nome}" onerror="this.remove()"><span class="portrait-initial">${suspect.nome[0]}</span></span><span><b>${suspect.nome}</b><small>${suspect.papel}</small></span><i>→</i>`; button.onclick = () => { area.querySelectorAll('.suspect').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderSuspect(suspect); document.querySelector('.question-panel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }; area.append(button); }); renderSuspect(data[0]); }).catch(() => { area.innerHTML = '<p>Não foi possível carregar os arquivos de interrogatório.</p>'; });

}
