const suspects = [
  ['camila-duarte', 'camila_duarte.png'], ['daniel-rocha', 'daniel_rocha.png'],
  ['rafael-martins', 'rafael_martins.png'], ['marina-albuquerque', 'marina_alburquerque.png'],
  ['helena-martins', 'helena_martins.png'], ['eduardo-alves', 'eduardo_alves.png'],
  ['gabriel-monteiro', 'gabriel_monteiro.png'], ['lucas-martins', 'lucas_martins.png']
];
const interrogations = {
  'camila-duarte': [
    { fase: 1, perguntas: [{ pergunta: 'Por que você entrou no banheiro depois que Rafael abriu a porta?', resposta: 'Eu fiquei muito abalada com o que vi e precisei me afastar por alguns minutos. Fui ao banheiro para respirar e tentar me acalmar.' }, { pergunta: 'O que aconteceu entre você e Isabela antes do apagão?', resposta: 'Nós discutimos. Ela descobriu que eu tinha contado uma coisa pessoal dela para outra pessoa e ficou muito magoada. Disse que já não sabia em quem podia confiar.' }] },
    { fase: 2, perguntas: [{ pergunta: 'A perícia encontrou seu sangue no banheiro. Você consegue explicar isso?', resposta: 'Eu me machuquei antes de chegar ao quarto e acabei usando o banheiro. Foi uma coisa pequena e achei que não tinha importância para mencionar.' }, { pergunta: 'O que exatamente você contou sobre Isabela para outra pessoa?', resposta: 'Eu contei que ela estava pensando em não se casar com Gabriel. Ela tinha começado a desconfiar dele e dizia que tinha descoberto coisas sobre o passado dele. Eu achei que ela só estivesse nervosa com o casamento.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Você percebeu alguma coisa estranha quando chegou ao quarto 307?', resposta: 'Naquele momento, eu estava mais preocupada com Isabela. Rafael estava tentando ajudar e todo mundo falava ao mesmo tempo. Só depois percebi que algumas coisas no quarto estavam fora do lugar.' }, { pergunta: 'Você viu alguém perto do quarto antes de entrar?', resposta: 'Vi algumas pessoas no corredor, mas estava tudo acontecendo muito rápido. Eu não prestei atenção suficiente para saber exatamente quem estava vindo de cada lugar.' }] }
  ],
  'rafael-martins': [
    { fase: 1, perguntas: [{ pergunta: 'As gavetas do quarto 307 foram encontradas mexidas. Você sabe o que Isabela guardava ali?', resposta: 'Alguns documentos pessoais, papéis do casamento e coisas que ela estava investigando. Eu não sabia exatamente o que ela tinha encontrado, mas sabia que ela estava guardando informações que poderiam causar problemas para algumas pessoas.' }, { pergunta: 'Quando você e Isabela discutiram sobre dinheiro, o que exatamente ela tinha descoberto?', resposta: 'Ela tinha percebido que havia coisas erradas na minha situação financeira. Disse que os números não batiam e que eu estava escondendo a verdadeira dimensão dos meus problemas. Eu achei que ela estava apenas desconfiada, mas pelo jeito ela já tinha encontrado alguma coisa.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Isabela estava reunindo provas contra você. Quem, além de você, sabia que ela estava fazendo isso?', resposta: 'Eu não sei exatamente quem sabia. Isabela não confiava em ninguém quando estava investigando alguma coisa. Mas, se ela já estava procurando documentos e fazendo anotações sobre as pessoas, é possível que alguém próximo tenha percebido o que ela estava fazendo.' }, { pergunta: 'Você entrou no quarto assim que a porta foi arrombada. O que você lembra sobre o armário de casacos naquele momento?', resposta: 'Eu estava preocupado com a Isabela e fui direto até ela. Não prestei atenção no armário. Só lembro que ele estava fechado quando olhei para o quarto depois que a situação começou a ser controlada.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Se alguém tivesse procurado alguma coisa no quarto naquela noite, o que você acha que essa pessoa estaria procurando?', resposta: 'Provavelmente alguma coisa que Isabela tinha descoberto. Ela estava juntando documentos e informações sobre várias pessoas. Se alguém entrou ali para procurar alguma coisa, não acho que estivesse atrás de dinheiro ou objetos pessoais.' }, { pergunta: 'Se você tivesse que apontar alguém que realmente tinha motivos para querer Isabela morta, quem seria?', resposta: 'Eduardo. Ele ainda tinha sentimentos por ela, não aceitava o casamento e foi a última pessoa que esteve sozinho com ela antes de tudo acontecer. Todo mundo está olhando para a minha situação financeira, mas Eduardo tinha muito mais a perder emocionalmente.' }] }
  ],
  'eduardo-alves': [
    { fase: 1, perguntas: [{ pergunta: 'Você disse que recebeu uma carta de Isabela pedindo que fosse ao hotel. O que exatamente estava escrito nela?', resposta: 'Era um pedido para que eu fosse ao hotel naquela noite, por volta das 21h, porque ela precisava conversar comigo pessoalmente. O pedido era direto e dizia para eu não chegar atrasado. Foi por isso que eu fui.' }, { pergunta: 'Quando você percebeu que Isabela não tinha chamado você, por que continuou a conversa?', resposta: 'Porque ela estava diferente e claramente havia alguma coisa acontecendo. Ela disse que não sabia mais em quem confiar e que estava começando a questionar algumas coisas que tinha descoberto.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Você disse que ouviu um barulho antes de sair do quarto. O que aconteceu exatamente?', resposta: 'Nós estávamos conversando quando ouvimos um barulho vindo de dentro do quarto, como se algum objeto tivesse caído. Isabela parou imediatamente e ficou olhando na direção de onde veio o som.' }, { pergunta: 'Você ainda tinha sentimentos por Isabela. O que vocês discutiram sobre Gabriel naquela noite?', resposta: 'Eu disse que achava que ela estava cometendo um erro ao se casar sem esclarecer algumas coisas sobre Gabriel. Ficou claro para mim que ela também estava desconfiada.' }] },
    { fase: 3, perguntas: [{ pergunta: 'Isabela recebeu uma mensagem dizendo “Você não sabe a história inteira”. Ela falou sobre isso?', resposta: 'Sim. Ela perguntou se eu sabia alguma coisa sobre aquilo. Eu disse que não tinha enviado a mensagem e que não sabia quem tinha escrito.' }, { pergunta: 'Se não foi você, quem poderia ter interesse em impedir Isabela de continuar investigando?', resposta: 'Rafael tinha um problema financeiro que poderia ficar muito maior se ela encontrasse provas. Gabriel também tinha motivos para estar preocupado, porque Isabela estava investigando o passado dele.' }] }
  ],
  'marina-albuquerque': [
    { fase: 1, perguntas: [{ pergunta: 'O telefone que enviou a mensagem “Você não sabe a história inteira” foi rastreado. Você enviou essa mensagem?', resposta: 'Enviei. Eu sabia que Isabela estava desconfiada de algumas coisas e achei que ela precisava saber que havia algo que ainda não tinha descoberto.' }, { pergunta: 'Naquela semana, Isabela estava investigando pessoas próximas. O que você percebeu?', resposta: 'Ela estava diferente. Fazia perguntas, observava as pessoas e parecia estar decepcionada com várias pessoas. Eu percebi que ela estava tentando descobrir mais sobre Gabriel.' }] },
    { fase: 2, perguntas: [{ pergunta: 'Por que você mandou uma mensagem anônima para Isabela em vez de falar pessoalmente?', resposta: 'Porque eu não queria ser colocada no meio do casamento. Se falasse diretamente, Isabela iria querer saber como eu descobri aquilo e Gabriel é meu irmão; isso destruiria nosso relacionamento.' }, { pergunta: 'Isabela chegou a perguntar a você alguma coisa sobre Gabriel antes de morrer?', resposta: 'Sim. Ela perguntou se eu sabia de alguma coisa que ela ainda não tinha descoberto sobre ele. Eu disse que não sabia de nada. Eu menti porque não estava preparada para contar.' }] },
    { fase: 3, perguntas: [{ pergunta: 'O que você sabia sobre Gabriel que Isabela ainda não sabia?', resposta: 'Eu sabia que Gabriel estava tendo um caso com outra mulher. Eu não sabia exatamente há quanto tempo aquilo acontecia, mas tinha motivos suficientes para ela cancelar o casamento.' }, { pergunta: 'Você chegou a descobrir como Isabela estava conseguindo informações sobre Gabriel?', resposta: 'Não exatamente. Acho que poderia ter vindo do Lucas, ele fica ouvindo escondido as pessoas conversando.' }] }
  ]
};
const access = document.querySelector('#case-access');
const showAccess = () => {
  access.innerHTML = `<div class="access-wrap"><article class="access-card" style="background-image:linear-gradient(to bottom,rgba(0,0,0,.02) 30%,rgba(0,0,0,.18) 52%,rgba(0,0,0,.96) 100%),url('../images/quarto307.png');background-size:cover;background-position:center"><div class="card-code">ARQ. 001</div><p>caso disponível agora</p><h2>O Quarto<br><em>307</em></h2><span class="card-arrow">↗</span></article><button class="access-open" type="button">ABRIR</button><div class="pin-area"><h2>Digite a senha</h2><p>Use o código de acesso do seu caso.</p><div class="pin-dots">○ ○ ○ ○</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n => `<button data-key="${n}">${n}</button>`).join('')}<button class="clear" data-key="clear">limpar</button><button data-key="0">0</button><button class="clear" data-key="back">←</button></div><div class="lock-error"></div></div></div>`;
  access.querySelector('.access-open').onclick = () => access.classList.add('show-pin');
  let pin = ''; const dots = access.querySelector('.pin-dots'), error = access.querySelector('.lock-error');
  access.querySelectorAll('[data-key]').forEach((button) => button.onclick = () => { const key = button.dataset.key; pin = key === 'clear' ? '' : key === 'back' ? pin.slice(0, -1) : pin.length < 4 ? pin + key : pin; dots.textContent = [0,1,2,3].map(i => i < pin.length ? '●' : '○').join(' '); if (pin.length === 4) { if (pin === '0307') { access.remove(); } else { error.textContent = 'senha incorreta · acesso negado'; pin = ''; setTimeout(() => dots.textContent = '○ ○ ○ ○', 450); } } });
};
showAccess();
document.querySelector('.exit-case').onclick = () => window.location.reload();

const questions = document.querySelector('#questions'), name = document.querySelector('#name'), role = document.querySelector('#role'), area = document.querySelector('#suspects');
const renderSuspect = (suspect) => {
  name.textContent = suspect.nome; role.textContent = `${suspect.papel} · ${suspect.idade} anos`; questions.innerHTML = '';
  const phases = interrogations[suspect.id] || suspect.fases;
  phases.forEach((phase) => { const group = document.createElement('div'); group.className = 'phase'; group.innerHTML = `<p>fase ${phase.fase} · escolha uma pergunta</p>`; phase.perguntas.forEach((item, index) => { const button = document.createElement('button'); button.innerHTML = `<i>${String(index + 1).padStart(2, '0')}</i>${item.pergunta}<strong>+</strong>`; button.onclick = () => { group.querySelectorAll('button').forEach(other => { other.disabled = true; other.style.opacity = other === button ? '1' : '.35'; }); button.classList.add('asked'); const response = document.createElement('div'); response.className = 'phase-answer'; response.innerHTML = `<span>resposta de ${suspect.nome}</span><p>“${item.resposta}”</p>`; group.append(response); }; group.append(button); }); questions.append(group); });
};
Promise.all(suspects.map(([id, photo]) => fetch(`suspeitos/${id}.json`).then(response => response.json()).then(data => ({ ...data, photo })))).then((data) => { area.innerHTML = ''; data.forEach((suspect, index) => { const button = document.createElement('button'); button.className = `suspect${index === 0 ? ' active' : ''}`; button.innerHTML = `<span class="suspect-no">${String(index + 1).padStart(2, '0')}</span><span class="portrait"><img src="images/${suspect.photo}" alt="Foto de ${suspect.nome}" onerror="this.remove()"><span class="portrait-initial">${suspect.nome[0]}</span></span><span><b>${suspect.nome}</b><small>${suspect.papel}</small></span><i>→</i>`; button.onclick = () => { area.querySelectorAll('.suspect').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderSuspect(suspect); document.querySelector('.question-panel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }; area.append(button); }); renderSuspect(data[0]); }).catch(() => { area.innerHTML = '<p>Não foi possível carregar os arquivos de interrogatório.</p>'; });
