const suspects = [
  ['camila-duarte', 'camila_duarte.png'], ['daniel-rocha', 'daniel_rocha.png'],
  ['rafael-martins', 'rafael_martins.png'], ['marina-albuquerque', 'marina_alburquerque.png'],
  ['helena-martins', 'helena_martins.png'], ['eduardo-alves', 'eduardo_alves.png'],
  ['gabriel-monteiro', 'gabriel_monteiro.png'], ['lucas-martins', 'lucas_martins.png']
];
const detailStyle = document.createElement('style');
detailStyle.textContent = `.statement{margin:18px 0;padding:21px 22px;background:linear-gradient(135deg,#211312,#151615);border-left:3px solid #b82a25}.statement span,.phase>p,.phase-answer span{display:block;margin:0 0 9px;color:#dc4b43;font:10px 'DM Mono';letter-spacing:1px;text-transform:uppercase}.statement p{margin:0;color:#e8dfd1;font:600 20px/1.45 'Playfair Display';white-space:pre-line}.phase{margin-top:18px;border-top:1px solid #51524e;padding-top:12px}.phase>p{color:#d5a96b}.phase-answer{margin-top:14px;padding:17px 18px;background:#30312e;border-left:3px solid #d5a96b}.phase-answer span{color:#d5a96b}.phase-answer p{font:600 20px/1.35 'Playfair Display';margin:8px 0 0}`;
document.head.append(detailStyle);
const access = document.querySelector('#case-access');
const showAccess = () => {
  access.innerHTML = `<div class="access-wrap"><article class="access-card" style="background-image:linear-gradient(to bottom,rgba(0,0,0,.02) 30%,rgba(0,0,0,.18) 52%,rgba(0,0,0,.96) 100%),url('../images/quarto307.png');background-size:cover;background-position:center"><div class="card-code">ARQ. 001</div><p>caso disponível agora</p><h2>O Quarto<br><em>307</em></h2><span class="card-arrow">↗</span></article><button class="access-open" type="button">ABRIR</button><div class="pin-area"><h2>Digite a senha</h2><p>Use o código de acesso do seu caso.</p><div class="pin-dots">○ ○ ○ ○</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n => `<button data-key="${n}">${n}</button>`).join('')}<button class="clear" data-key="clear">limpar</button><button data-key="0">0</button><button class="clear" data-key="back">←</button></div><div class="lock-error"></div></div></div>`;
  access.querySelector('.access-open').onclick = () => access.classList.add('show-pin');
  let pin = ''; const dots = access.querySelector('.pin-dots'), error = access.querySelector('.lock-error');
  access.querySelectorAll('[data-key]').forEach((button) => button.onclick = () => { const key = button.dataset.key; pin = key === 'clear' ? '' : key === 'back' ? pin.slice(0, -1) : pin.length < 4 ? pin + key : pin; dots.textContent = [0,1,2,3].map(i => i < pin.length ? '●' : '○').join(' '); if (pin.length === 4) { if (pin === '0307') { sessionStorage.setItem('quarto307', 'ok'); access.remove(); } else { error.textContent = 'senha incorreta · acesso negado'; pin = ''; setTimeout(() => dots.textContent = '○ ○ ○ ○', 450); } } });
};
if (sessionStorage.getItem('quarto307') === 'ok') access.remove(); else showAccess();
document.querySelector('.exit-case').onclick = () => { sessionStorage.removeItem('quarto307'); window.location.reload(); };

const questions = document.querySelector('#questions'), answer = document.querySelector('#answer'), name = document.querySelector('#name'), role = document.querySelector('#role'), area = document.querySelector('#suspects');
const renderSuspect = (suspect) => {
  name.textContent = suspect.nome; role.textContent = `${suspect.papel} · ${suspect.idade} anos`; questions.innerHTML = ''; answer.innerHTML = '<span>resposta</span><p>Escolha uma pergunta para consultar o depoimento.</p>';
  const statement = document.createElement('div'); statement.className = 'statement'; statement.innerHTML = `<span>depoimento inicial · ${suspect.nome}</span><p></p>`; questions.append(statement);
  statement.querySelector('p').textContent = suspect.depoimento || 'Este depoimento ainda está sendo preparado pelo investigador.';
  suspect.fases.forEach((phase) => { const group = document.createElement('div'); group.className = 'phase'; group.innerHTML = `<p>fase ${phase.fase} · escolha uma pergunta</p>`; phase.perguntas.forEach((item, index) => { const button = document.createElement('button'); button.innerHTML = `<i>${String(index + 1).padStart(2, '0')}</i>${item.pergunta}<strong>+</strong>`; button.onclick = () => { group.querySelectorAll('button').forEach(other => { other.disabled = true; other.style.opacity = other === button ? '1' : '.35'; }); button.classList.add('asked'); const response = document.createElement('div'); response.className = 'phase-answer'; response.innerHTML = `<span>resposta de ${suspect.nome}</span><p>“${item.resposta}”</p>`; group.append(response); }; group.append(button); }); questions.append(group); });
};
Promise.all(suspects.map(([id, photo]) => fetch(`suspeitos/${id}.json`).then(response => response.json()).then(data => ({ ...data, photo })))).then((data) => { area.innerHTML = ''; data.forEach((suspect, index) => { const button = document.createElement('button'); button.className = `suspect${index === 0 ? ' active' : ''}`; button.innerHTML = `<span class="suspect-no">${String(index + 1).padStart(2, '0')}</span><span class="portrait"><img src="images/${suspect.photo}" alt="Foto de ${suspect.nome}" onerror="this.remove()"><span class="portrait-initial">${suspect.nome[0]}</span></span><span><b>${suspect.nome}</b><small>${suspect.papel}</small></span><i>→</i>`; button.onclick = () => { area.querySelectorAll('.suspect').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderSuspect(suspect); document.querySelector('.question-panel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }; area.append(button); }); renderSuspect(data[0]); }).catch(() => { area.innerHTML = '<p>Não foi possível carregar os arquivos de interrogatório.</p>'; });
